studySpec:
  metrics:
  - metricId: map_at_10
    goal: MAXIMIZE
  parameters:
  - parameterId: iterations
    discreteValueSpec:
      values:
      - 10
      - 20
  - parameterId: regularization
    doubleValueSpec:
      minValue: 1.0e-4
      maxValue: 1.0e-1
    scaleType: UNIT_LINEAR_SCALE
  algorithm: ALGORITHM_UNSPECIFIED # results in Bayesian optimization
trialJobSpec:
  workerPoolSpecs:  
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: gcr.io/qwiklabs-asl-04-5e165f533cac/trainer_image
      args:
      - --job_dir=$JOB_DIR
      - --training_dataset_path=$TRAINING_FILE_PATH
      - --validation_dataset_path=$VALIDATION_FILE_PATH
      - --hptune