
FROM gcr.io/deeplearning-platform-release/base-cpu
RUN pip install kfp==1.6.6
RUN pip install google-cloud-aiplatform==1.3.0
RUN pip install -U google-cloud-pipeline-components==0.2.1

ENTRYPOINT ["/bin/bash"]
